### ISSUE TITLE
E486:找不到模式:soclet

### ISSUE THREAD

**Issue by shenxixi250** [lilydjwg/fcitx.vim#12]
您好感谢您的回复 完整的信息就是E486:找不到模式:soclet 插件不起作用 切换模式 vim状态栏就回提示这个信息 然后就没有了 vim启动也没有报错  安装插件也没有报错

**Comment by shenxixi250** [comment]
安装使用的是vundle直接pulgin'lilydjwg/fcitx.vim'   后来报错找不FCITX_SOCKET然后也不知道要配什么就看了你的 博客是/tmp文件中的  我就把它配成/tmp/fcitx-socket-:0的这个文件 加入到etc/profile中去  然后它切换模式就会报上面的错误   help thx

**Comment by shenxixi250** [comment]
ubuntu18  fcitx4.2

**Comment by lilydjwg** [comment]
请贴完整的报错信息。

**Comment by shenxixi250** [comment]
您好感谢您的回复 完整的信息就是E486:找不到模式:soclet 插件不起作用 切换模式 vim状态栏就回提示这个信息 然后就没有了 vim启动也没有报错 安装插件也没有报错

**Comment by lilydjwg** [comment]
呃，你会截图吗？

**Comment by shenxixi250** [comment]
![图片](https://user-images.githubusercontent.com/48914848/66467884-c5cd6d80-eab7-11e9-863a-acbc385c8d77.png)

**Comment by shenxixi250** [comment]
总的来说就是 vim.fictx没有起作用 进入vim后也是sogou拼音然后打字母 就会出现这种情形
![图片](https://user-images.githubusercontent.com/48914848/66468183-560bb280-eab8-11e9-8680-7ab0a3ecbedd.png)

**Comment by lilydjwg** [comment]
这报错连行号都没有……它并不像是 fcitx.vim 报出来的。

```
:echo g:loaded_fcitx $DISPLAY $FCITX_SOCKET executable('fcitx5-remote')
```

显示什么？

**Comment by shenxixi250** [comment]
![图片](https://user-images.githubusercontent.com/48914848/66534344-826f0f80-eb48-11e9-96df-b3c1500b1c80.png)

**Comment by shenxixi250** [comment]
这是不是可能我的sogou有问题啊

**Comment by lilydjwg** [comment]
在中文输入状态下按一下 Ctrl-Alt-P 再试试？

**Comment by shenxixi250** [comment]
Oh it`s not work     and  when i press "nihao" in normal mode with sogou  .
![图片](https://user-images.githubusercontent.com/48914848/66544272-46e53d00-eb6a-11e9-8983-45df1bb1d377.png)
i donot know      and     the  <++>   is  a  shortcut key  that i add it with markdown in vim 
![图片](https://user-images.githubusercontent.com/48914848/66544530-01753f80-eb6b-11e9-9bd4-6881da22bf05.png)
vim is difficult for me      Maybe   it is good idea to learn english well
