### ISSUE TITLE
esc切换到英文速度很慢

### ISSUE THREAD

**Issue by 1322739583** [lilydjwg/fcitx.vim#13]
按esc切换到英文很慢，大概要2、3秒;恢复为原来的状态很快，秒切。本来就是这样,还是就我的有问题？google拼音和系统默认的拼音输入法都是这样。应该不是输入法问题。
系统：Majaro 18.1.5
vim版本:vim8.1

**Comment by lilydjwg** [comment]
设置一个较小的 'ttimeoutlen' 值。如果你在 screen / tmux 里使用，也要相应的调整一下设置。

**Comment by 1322739583** [comment]
谢谢 ！ 我试下

**Comment by 1322739583** [comment]
解决了 感谢！
