### ISSUE TITLE
无报错但无法使用

### ISSUE THREAD

**Issue by niuiic** [lilydjwg/fcitx.vim#14]
我的操作系统：arch linux + dde desktop
前提：fcitx-remote和fcitx5-remote均正常
我的尝试：
1.一开始我使用fcitx作为输入法，然后使用vim-plug从github安装fcitx.vim，无报错，但没有任何效果
2.尝试从https://www.vim.org/scripts/script.php?script_id=3764 下载1.2.6版本，按您的指示解压到~/.vim，情况依旧如上，此时我使用neovim，意识到放错了位置，纠正后依旧如上
3.尝试直接将您在plug/fcitx.vim的内容写入~/.config/nvim/init.vim，当我试图重新用nvim打开一个文件时，报错如下，同时该错误在我进行该操作之前用nvim打开您的plug/fcitx.vim时同样存在

**************
Error detected while processing modelines:
line  248:
E992: Not allowed in a modeline when 'modelineexpr' is off: fde=getline(v:lnum-1)=~'\\v"\\s*-{20,}'?'>1':1
***************

报错的是最后一行，一行注释，`  248 " vim:fdm=expr:fde=getline(v\:lnum-1)=~'\\v"\\s*-{20,}'?'>1'\:1
`，去掉"后依旧报错，删除该行后不再报错
同时，还有一个错误，init.py不存在，于是把您的fcitx.py移动到init.vim所在目录，修改为init.py，不再报错

这里顺便运行了一下这个python文件，`ModuleNotFoundError: No module named 'vim'`，这样看来您不是为neovim设计的，不过后来我又尝试了vim，所以还是补全了这个模块

至此，再无报错，但依旧无法使用

4.尝试使用fcitx5，重复 1 2 3，依旧如上
5.尝试使用vim，重复1 2 3，依旧如上
6.按您的博客设置了FCITX_SOCKET，依旧如上

**Comment by lilydjwg** [comment]
你试了好多组合。

那个 modeline 删掉吧，不影响的。你先贴一下` vim --version`？（是的，不支持 neovim；也许它能用，也许不能。）

**Comment by niuiic** [comment]
感谢您的回答，我已经把vim卸了，不过我想您了解arch，安装的绝对是最新版，我查看到版本为vim-8.2.0717-2

**Comment by niuiic** [comment]
重新安装了vim,并附上vim --version

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  8 2020 23:37:13)
包含补丁: 1-717
编译者 Arch Linux
巨型版本 无图形界面。  可使用(+)与不可使用(-)的功能:
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       +tcl/dyn
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl/dyn          +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              +mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
     系统 vimrc 文件: "/etc/vimrc"
     用户 vimrc 文件: "$HOME/.vimrc"
 第二用户 vimrc 文件: "~/.vim/vimrc"
      用户 exrc 文件: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
         $VIM 预设值: "/usr/share/vim"
编译方式: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
链接方式: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lelf    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.30/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm  
```

**Comment by lilydjwg** [comment]
加载后，执行

```
:echo g:loaded_fcitx
:py3 print(fcitxsocketfile)
:py3 print(Fcitx.status())
```

看看输出是什么样的。

**Comment by niuiic** [comment]
（1）`:echo g:loaded_fcitx`在英文输入法下为1，另外，如果在输入之后执行之前把输入法切换为中文，依旧为1（中文状态下无法输入: ，我觉得这应该是正常的）
（2）`:py3 print(fcitxsocketfile)`
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'fcitxsocketfile' is not defined
```
（3）`:py3 print(Fcitx.status())`同样的错误，Fcitx is not defined
（4）`:echo has("python3")`，1

另外还有一些

0.现在的情况是我重装了vim，.vimrc里什么也没有，1.2.6版本解压到了.vim下
1. 我把之前的FCITX_SOCKET的设置给删了
2. 安装了python-vim，我查到的python的vim模块是这个，来自 https://yianwillis.github.io/vimcdoc/doc/if_pyth.html ，不过再次运行fcitx.py时有以下错误（刚才忘了说，其实之前也有）
```
Traceback (most recent call last):
  File "fcitx.py", line 9, in <module>
    fcitxsocketfile = vim.eval('s:fcitxsocketfile')
AttributeError: module 'vim' has no attribute 'eval'
```
这看起来感觉是我装错了，但我暂时没有在网上找到其他的，于是又安装了vim --version中显示支持的python3/dyn，不过这显然不是

请指教

**Comment by lilydjwg** [comment]
说明 Python 脚本没有加载。这种情况下应该有报错啊。

你改一下 plugin/fcitx.vim，在第53行前加上 `:echo pyfile` 看看路径是否正常（指向同一目录里的 fcitx.py）？然后你执行 `:py3file 路径` 会有报错吗？不报错的话，`:py3 print(fcitxsocketfile)` 还报错吗？

**Comment by niuiic** [comment]
加了`:echo pyfile`后没有发生什么，依旧无报错

`:py3file`的结果
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/niuiic/.vim/plugin/fcitx.py", line 9, in <module>
    fcitxsocketfile = vim.eval('s:fcitxsocketfile')
vim.error: Vim:E121: 未定义的变量: s:fcitxsocketfile
```

`:py3 print(fcitxsocketfile)`的结果
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'fcitxsocketfile' is not defined
```

**Comment by lilydjwg** [comment]
哦对，那个 Python 文件里引用了 `s:` 变量，你直接加载不上的。

`:echo pyfile` 看不到么，那你删掉 fcitx.vim 最后边的 `unlet pyfile` 然后再在 Vim 里交互式地 echo 它呢？

**Comment by niuiic** [comment]
我删除了`unlet pyfile`，结果为未定义的变量pyfile，然后我又加上了，还是同样的结果

关于pyfile,文件中全部的5个位置

```
let pyfile = expand('<sfile>:r') . '.py'
    1 if python3
  54    exe 'py3file' pyfile
    1   au InsertLeave * py3 fcitx2en()
    2   au InsertEnter * py3 fcitx2zh()
    3 else
    4   exe 'pyfile' pyfile
    5   au InsertLeave * py fcitx2en()
    6   au InsertEnter * py fcitx2zh()
    7 endif
    8 " ---------------------------------------------------------------------
    9 "  Restoration And Modelines:
   10 unlet python3
   11 unlet pyfile
```

此外我有一个疑问，参考[arch wiki](https://wiki.archlinux.org/index.php/Fcitx_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#Vim)（见4.2条）可知，仅在.vimrc中设置一段代码即可实现切换，就类似您在so文件夹下的那一份，但经尝试后发现不行（此时我使用的是vim+fcitx），是否还可能是其他的原因呢

**Comment by lilydjwg** [comment]
啊咧，你在终端执行 `fcitx-remote`试试？

**Comment by niuiic** [comment]
`fcitx-remote`和`fcitx5-remote`以及`-o`，`-c`选项均正常，这我在之前就已经测试过

**Comment by lilydjwg** [comment]
所以你是用的 fcitx4 还是 fcitx5？

**Comment by niuiic** [comment]
两者是冲突的，我只能拆卸其中之一并重装另一个，我的意思是两个版本测试结果都正常

**Comment by lilydjwg** [comment]
Python 版本不支持 fcitx5 的，只支持 fcitx4。

要不你 `:set verbose=20 verbosefile=/tmp/vim.log` 看看执行过程吧。

**Comment by niuiic** [comment]
我暂时无法尝试

补充两点：
1. 我可以确定vim加载了fcitx.vim，因为当.vim下存在fcitx.vim且在.vimrc中写入切换的代码时有报重复的错误，至于.py，应该是没有，我的理解，python是为了更好的体验，但没有这个也能跑，至少我copy arch wiki下的代码无效，说明这里就出了点问题
2. vim配置失败后，我尝试了一下jetbrians系列的ideavim extension插件，用于在clion中自动切换输入法（意外发现了该系列ide无法输入中文，不过，修好了，但有可能拖累了该插件），但在fcitx4和fcitx5下也不行，可能与您的插件存在共同的错误，我指的是linux下fcitx输入法方面的错误，在windows 10下ideavim extension完全没有问题

**Comment by lilydjwg** [comment]
你是怎么进入和退出插入模式的？

**Comment by niuiic** [comment]
进入普通模式我一般使用ctrl+c（换了左ctrl和alt），不过我考虑到这个可能，所以用esc也试过，进入插入模式没什么特别的，无非就是那几个键

我有考虑到可能是我进入退出输入速度太快，插件反应没跟上，输入法没切换，所以也试过等一会儿再输入，不过无效，当然如果真有这样的情况，我觉得也是设计不合理的，要慢也得是先切输入法在切模式呀

**Comment by lilydjwg** [comment]
使用 Ctrl-C 退出插入模式时，本插件（以及很多依赖 InsertLeave 事件的插件）将无法工作。

**Comment by niuiic** [comment]
嗯，不过上面提到了esc也没用

我没有研究这两个指令有什么区别，我使用的另外两个插件vscode vim插件自带的切换（仅支持windows）以及win10下的ideavim extension都可识别ctrl + c，我想这应该不是主要原因

**Comment by lilydjwg** [comment]
> 我没有研究这两个指令有什么区别，我使用的另外两个插件vscode vim插件自带的切换（仅支持windows）以及win10下的ideavim extension都可识别ctrl + c，我想这应该不是主要原因

这些跟 Vim 有什么关系？你想？Vim 是你写的么？

> 嗯，不过上面提到了esc也没用

那就重新测试一下，你的环境多变（vim vs neovim；fcitx4 vs fcitx5），我不知道你测试了多少种组合，有没有涵盖我预期的那个。

另外给一下 :au InsertLeave 的输出。

-- 
Best regards,
lilydjwg

**Comment by niuiic** [comment]
> 这些跟 Vim 有什么关系？你想？Vim 是你写的么？
两个vim插件倒是和元生vim确实没关系，而且我查了一下，确实无法触发InsertLeave事件，嗯，不知您是否有意向在下个版本把这个指令弄进去

> 那就重新测试一下，你的环境多变（vim vs neovim；fcitx4 vs fcitx5），我不知道你测试了多少种组合，有没有涵盖我预期的那个。

只有四种组合，之前都试过，重新测试，在vim+fcitx5下，和之前的结果完全不同，现在似乎好了！！！

```
:au InsertLeave
--- 自动命令 ---
InsertLeave
    *         call Fcitx2en()
```

嗯，看来暂时已经没有问题了，非常感谢您的帮助

**Comment by niuiic** [comment]
> 这些跟 Vim 有什么关系？你想？Vim 是你写的么？
两个vim插件倒是和元生vim确实没关系，而且我查了一下，确实无法触发InsertLeave事件，嗯，不知您是否有意向在下个版本把这个指令弄进去

> 那就重新测试一下，你的环境多变（vim vs neovim；fcitx4 vs fcitx5），我不知道你测试了多少种组合，有没有涵盖我预期的那个。

只有四种组合，之前都试过，重新测试，在vim+fcitx5下，和之前的结果完全不同，现在似乎好了！！！

```
:au InsertLeave
--- 自动命令 ---
InsertLeave
    *         call Fcitx2en()
```

嗯，看来暂时已经没有问题了，非常感谢您的帮助
