### ISSUE TITLE
rime输入法没有效果

### ISSUE THREAD

**Issue by 1322739583** [lilydjwg/fcitx.vim#16]
之前用过这个插件，当时用的是一个google拼音，一个英文输入法，使用shift切换输入法。是可以用的。
后来重装了manjaro，使用了rime输入法（只有一个输入法，没有添加单独的英文输入法），使用shift在rime输入法内部切换中英文。安装这个插件按esc没有变成英文状态。

我添加系统默认的拼音和默认的英文输入法，也是没有效果的。

vim和nvim都是不行的。

fcitx版本：4.2.9.7
manajro:20
桌面环境：kde5
vim环境：vim8 nvim 0.4.4

**Comment by lilydjwg** [comment]
是的，fcitx.vim 是切换 fcitx 的状态的，没办法切换 rime 的状态。

**Comment by 1322739583** [comment]
非常感谢！
我找到了解决办法！
**在***.custom.yaml下添加代码：
  "key_binder/bindings":
    - { when: always, accept: Release+Escape, toggle: ascii_mode}**
可以实现一样的效果。
遇到同样的问题的小伙伴可以参考下。

不知道作者可不可以加入对rime的兼容支持。

**Comment by lilydjwg** [comment]
> 不知道作者可不可以加入对rime的兼容支持。

不可以，除非 rime 有提供查询和切换输入法状态的接口。

**Comment by haolian9** [comment]
> 不可以，除非 rime 有提供查询和切换输入法状态的接口。

现在还真有了，fcitx5-rime 提供了一些 dbus 接口（[具体见](https://github.com/fcitx/fcitx5-rime/issues/30#issuecomment-957001110))，应该能用上

**Comment by lilydjwg** [comment]
@haolian9 请测试 [fcitx5-rime](https://github.com/lilydjwg/fcitx.vim/tree/fcitx5-rime) 分支。设置

```
let g:fcitx5_rime = 1
```

以使用 rime 接口。

**Comment by haolian9** [comment]
<details>
<summary> 弯路</summary>
荣幸！虽然我可能不是最佳的测试人选。我仔细测了下，不知是不是配置问题，没有观察到“切换到 normal mode，rime 自动切换到 ascii mode”。
我的测试环境是：
* nvim 0.8.0 has('python3')
* pynvim 0.4.3
* dbus-python 1.3.2
* fcitx.vim branch=fcitx5-rime
* nvim +'let g:fcitx5_rime = 1'

nvim 中的操作流程：
* 初始状态：nvim 处于 normal mode，rime 处于 ascii mode
* `normal i` 此时 rime 处于 ascii mode
* `<shift>` 此时 rime 处于 `!`ascii mode
* `i_ctrl-o` 回到 normal mode，此时 rime 处于 `!`ascii mode

其他信息：
```
InsertEnter
    *         call Fcitx2zh()
InsertLeavePre
    *         call Fcitx2en()
```
shift 是我用来切换 rime ascii mode 的按键绑定
</details>

结果是我应该把 g:fcitx5_rime 放到配置文件中，`+'let ...'` 时机不对，哈哈。我这里用着没啥问题！

**Comment by haolian9** [comment]
看了下`plugin/fcitx.py`，我单择出来运行了：
```
> python
Python 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dbus
>>> sb = dbus.SessionBus()
>>> sb.get_object('org.fcitx.Fcitx5', '/controller')
<ProxyObject wrapping <dbus._dbus.SessionBus (session) at 0x7efec5c8c360> :1.3817 /controller at 0x7efec5b15cc0>
>>> obj = _
>>> fcitx =dbus.Interface(obj, dbus_interface='org.fcitx.Fcitx.Controller1')
>>> fcitx.state()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/playground/xx/venv/lib/python3.10/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/srv/playground/xx/venv/lib/python3.10/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/srv/playground/xx/venv/lib/python3.10/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method state or interface org.fcitx.Fcitx.Controller1.
```
实际提供的接口是这样的
```
> busctl introspect --user org.fcitx.Fcitx5 /rime
NAME                                TYPE      SIGNATURE RESULT/VALUE FLAGS
org.fcitx.Fcitx.Rime1               interface -         -            -
.GetCurrentSchema                   method    -         s            -
.IsAsciiMode                        method    -         b            -
.ListAllSchemas                     method    -         as           -
.SetAsciiMode                       method    b         -            -
.SetSchema                          method    s         -            -
org.freedesktop.DBus.Introspectable interface -         -            -
.Introspect                         method    -         s            -
org.freedesktop.DBus.Peer           interface -         -            -
.GetMachineId                       method    -         s            -
.Ping                               method    -         -            -
org.freedesktop.DBus.Properties     interface -         -            -
.Get                                method    ss        v            -
.GetAll                             method    s         a{sv}        -
.Set                                method    ssv       -            -
.PropertiesChanged                  signal    sa{sv}as  -            -

```

**Comment by lilydjwg** [comment]
好，我把修改合并到主分支上了。

**Comment by haolian9** [comment]
容许我跑个题：我觉得 nvim 下可以利用 lua ffi 直接调 libnotify 或者用其他语言调 libnotify 再借助 lua 的 c api 生成可以被 lua require 的 shared object。这两种方式都能舍掉对 python 的依赖，毕竟它配置起来还挺烦的，同时（也）可以重用 dbus 连接。（我不是在说 fcitx.vim 要这样实现哈，只是设想下针对 nvim 实现的优化，我确实是这么做的）

**Comment by lilydjwg** [comment]
python 正常系统都自带了呀。另外这里 dbus 连接是重用的。

**Comment by haolian9** [comment]
谢谢回复。（我上条信息中少了个“也”）
