### ISSUE TITLE
关于 ttimeoutlen

### ISSUE THREAD

**Issue by bommbo** [lilydjwg/fcitx.vim#17]
https://github.com/skywind3000/vim-quickui
这个老哥的插件理念貌似跟你相克，假如将 timeoutlen设置的过小，那么上面链接的那款插件就无法打开了。
就比如，这样的快捷键设置，nnoremap <silent><space><space> :call quickui#menu#open()<cr>。
另外，vnoremap <Leader>y "+y 这样的也失效。

**Comment by lilydjwg** [comment]
请问你的 Vim 的具体版本、终端名称及版本、操作系统名称及版本、fcitx 版本、「失效」时你具体看到的现象？

**Comment by bommbo** [comment]
老哥，你试一下vnoremap y "+y 这个本来用来方便复制到系统粘贴版的，如果设置timeoutlen过小，这个功能就会失效。我用的是manjaro+alacritty+neovim-nigtly-git。实际上如果不设定timeoutlen,您这插件也能用，但我试了下timeoutlen=100，它可能会造成其他映射失效，准确说应该是手速快也有效，但有其他映射会不好用

**Comment by lilydjwg** [comment]
到底是 ttimeoutlen 还是 timeoutlen 引发的问题？过小又是多小？给一个完整的最小重现案例？
`:echo has('python3')` 返回几？fcitx4 还是 fcitx5？
