### ISSUE TITLE
`InsertLeavePre` is not a defined vim event

### ISSUE THREAD

**Issue by CosmosAtlas** [lilydjwg/fcitx.vim#18]
On line 18 of `fcitx.vim` on branch `fcitx5`
```
    au InsertLeavePre * py3 fcitx2en()
```
throws an error about no such event.

Changing to `InsertLeave` fixes the problem and the plugin works successfully (at least on my machine).

`InseartLeavePre`在vim里面没有这个event，换成`InsertLeave`可以解决这个问题。

**Comment by lilydjwg** [comment]
Try latest.

**Comment by CosmosAtlas** [comment]
I can confirm it works now.

I searched a bit more. I guess I finally met something that's different in vim and neovim now! At least the current versions on Arch linux. Haha.
