### ISSUE TITLE
在检测到fcitx（中文）输入时禁用英文拼写检查

### ISSUE THREAD

**Issue by Davidyz** [lilydjwg/fcitx.vim#19]
英文拼写检查在中文输入时会把所有汉字识别为拼写错误，希望能加入在检测到中文输入时禁用拼写检查的功能。

**Comment by lilydjwg** [comment]
「检测到中文输入」这个真不是能随时检测到的。倒是可以在 `InsertEnter` 事件时，如果要激活输入法，那么可以关闭 spell。比如这样：

```
au InsertEnter * if py3eval('Fcitx.status()') | setl nospell | endif
```

你也可以通过 D-Bus 监听 fcitx5 的状态事件，在合适的时候更新 Vim 的选项。

这个需求太 specific 了，我不会直接加入。

**Comment by Davidyz** [comment]
好的，谢谢。我自己试一下
