### ISSUE TITLE
can I diable 'org.freedesktop.DBus.Error.NotSupported' warning?

### ISSUE THREAD

**Issue by xubury** [lilydjwg/fcitx.vim#22]
When I run neovim from windows terminal, a warning like below will pop up, can I disable it?
`fcitx.vim not loaded: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead`
I guess this only happens when there is no destop environment. The warning won't show up when I use neovim from Xserver.

**Comment by lilydjwg** [comment]
I just added this. You `let g:silent_unsupported = 1` in your .vimrc and that warning won't be printed.

This only happens when you don't have a D-Bus session daemon correctly setup. If you're running systemd, you should get it even without a desktop environment. Maybe you're using WSL? It'd be better if we can detect this situation.

**Comment by xubury** [comment]
yeah, I am using WSL2.

**Comment by xubury** [comment]
> I just added this. You `let g:silent_unsupported = 1` in your .vimrc and that warning won't be printed.
> 
> This only happens when you don't have a D-Bus session daemon correctly setup. If you're running systemd, you should get it even without a desktop environment. Maybe you're using WSL? It'd be better if we can detect this situation.

Yes, I can confirm it is caused by not having dbus daemon because systemd wasn't running on WSL2. 
There's a workaround for running systemd on WSL2: https://github.com/arkane-systems/genie

**Comment by lilydjwg** [comment]
You don't need systemd to use fcitx.vim. I was just curious who's not running systemd.

I never considered WSL2 for fcitx.vim. Is it still useful there?

**Comment by xubury** [comment]
> You don't need systemd to use fcitx.vim.

I know, but dbus-daemon is launched by systemd right? I am a newbie to linux system. 
I read that systemd is broken in WSL2:https://github.com/systemd/systemd/issues/8036
So after setting up the genie workaround, the warning is gone.
It is more of a systemd issue not fcitx.vim.
