### ISSUE TITLE
the name org.fcitx.fcitx5 was not provided by any .service files

### ISSUE THREAD

**Issue by b1ueb1ues** [lilydjwg/fcitx.vim#23]
新的更新似乎与fcitx4冲突了. 
搜狗输入法使用的是fcitx4似乎无法升级至5
我切换到vim-scripts/fcitx.vim问题可以解决.

**Comment by lilydjwg** [comment]
fcitx5 分支本来就不支持 fcitx4。请使用 fcitx4 分支。
