### ISSUE TITLE
fcitx5+ssh场景实现

### ISSUE THREAD

**Issue by tkkcc** [lilydjwg/fcitx.vim#25]
fcitx5分支中的通信通过dbus，请问如何单独控制本插件连接到远程dbus呢。

**Comment by lilydjwg** [comment]
可以用 fcitx5-server 分支。不过目前代码里硬编码了监听位置，你可以自己改一下。

**Comment by tkkcc** [comment]
感谢，我试下

**Comment by tkkcc** [comment]
纯本地用是有效，但本地ssh远程用还是不成功。我理解的是fcitx-status是在本地运行的，监听本地的\0fcitx-status，但如何把远程状态转发到本地的\0fcitx-status呢。我尝试了ssh配置`RemoteForward /home/REMOTE_USERNAME/\0fcitx-status /home/LOCAL_USERNAME/\0fcitx-status`，但远程vim仍然提示找不到\0fcitx-status。

**Comment by lilydjwg** [comment]
你用 ssh 的话就不要用抽象套接字（以 `\0` 开头）了呀，指定一个正常的 socket 文件吧。

**Comment by tkkcc** [comment]
成功了，感谢！
