### ISSUE TITLE
启动耗时较多

### ISSUE THREAD

**Issue by tkkcc** [lilydjwg/fcitx.vim#26]
使用本插件后感觉vim启动速度明显变慢，使用vim-plugins-profile测试发现本插件耗时65ms
```txt
~ python vim-plugins-profile.py                                      (bilabila)
Running vim to generate startup logs... done.
Loading and processing logs... done.
Plugin directory: /home/bilabila/.config/nvim/plugged
====================================
Top 10 plugins slowing vim's startup
====================================
1        65.050   fcitx.vim
2         2.652   nvim-compe
3         1.717   vim-visual-multi
4         1.551   nvim-treesitter-context
5         1.190   nvim-treesitter
6         0.802   vim-autoformat
7         0.524   vim-indentwise
8         0.331   vim-expand-region
9         0.313   vim-surround
10        0.294   vim-tmux-navigator
```
有无方法优化？

**Comment by lilydjwg** [comment]
因为要启动 Python provider 吧。你这不是 vim 慢，而是 neovim 慢。它们不是一回事。

**Comment by tkkcc** [comment]
确实是neovim慢。python启动耗时这么多，那可以做成异步加载 或者 专为neovim用lua实现一个插件？

**Comment by lilydjwg** [comment]
我不了解异步加载，也没有精力为 neovim 开发。你如果有兴趣，可以自行开发一个。

**Comment by tkkcc** [comment]
好的，有空我会尝试下。

**Comment by moetayuko** [comment]
使用`vim-plug`的话可以把加载延迟到第一次进入插入模式：
(Ref: https://github.com/junegunn/vim-plug/issues/53)
```viml
Plug 'lilydjwg/fcitx.vim', { 'on': [] }
augroup load_fcitx
  autocmd!
  autocmd InsertEnter * call plug#load('fcitx.vim') | autocmd! load_fcitx
augroup END
```
功能似乎正常

**Comment by tkkcc** [comment]
@MoetaYuko 
那样你第一次使用插入模式就会卡，如果还是要用python。
换到fcitx5后，不会用python，不会感知到卡顿。

**Comment by tkkcc** [comment]
nvim也有lua方案，https://github.com/h-hg/fcitx.nvim
当然实际使用不会感觉到区别。

**Comment by moetayuko** [comment]
> @MoetaYuko 那样你第一次使用插入模式就会卡，如果还是要用python。 换到fcitx5后，不会用python，不会感知到卡顿。

第一次使用插入模式倒是没有感知较强的卡顿，但fcitx5-remote的确更好（之前没注意到有这么个选项...

**Comment by Freed-Wu** [comment]
> 专为neovim用lua实现一个插件？

That's for you: [ime.nvim](https://github.com/Freed-Wu/ime.nvim) (powered by dbus, like fcitx.vim)

[fcitx.nvim](https://github.com/h-hg/fcitx.nvim) don't use dbus.
