### ISSUE TITLE
How to specify environment variable $FCITX_SOCKET

### ISSUE THREAD

**Issue by ArchitectBeaver** [lilydjwg/fcitx.vim#3]
Hi, I am really enjoying using this wonderful plugin to input Chinese characters.
I don't much about socket file and can not figure out how to set the environment variable $FCITX_SOCKET in this new version.
Could you please give an example about how to specify environment variable $FCITX_SOCKET?
I am currently using `Ubuntu 16.04 LTS 64bit` and `Vim 8.0`. Thanks.

**Comment by lilydjwg** [comment]
Generally you don't need to.

This variable is mainly used when you ssh into a remote system and want the Vim there to be able to control fcitx. Like this:

```bash
local $ ssh -R '/run/user/1000/fcitx-work.sock:/tmp/fcitx-socket-\:0' -Y remote
# ^--- This only works with recent openssh versions
remote $ export FCITX_SOCKET=/run/user/1000/fcitx-work.sock DISPLAY=:10
remote $ vim
# ^--- now vim can access both clipboards and fcitx
```

**Comment by ArchitectBeaver** [comment]
Thanks for your detailed reply. It resolved my puzzle.
