### ISSUE TITLE
nvim lua 配置下如何 生效 

### ISSUE THREAD

**Issue by ifnk** [lilydjwg/fcitx.vim#31]
### vim 配置 
 
![image](https://user-images.githubusercontent.com/39295458/158950435-9bb04115-fb83-406e-8821-9f4b1da962a5.png)

### fcitx 5 配置  
安装了  fcitx5  和 fcitx5-rime 
配置如下 
![image](https://user-images.githubusercontent.com/39295458/158950611-ec9f97af-b612-4437-894e-39e37751e3b0.png)

用了aur 的 小鹤双拼 paru -S rime-flypy 

### nvim 下的表现 

packersync 后 packerInstall 然后 重启 nvim 在 normal 为英文模式 按 i 切换到 中文模式 打中文 ，然后 esc 退出后 

它还是中文模式 ，不是期待 的英文模式 

请问我是哪里设置的不对么？

**Comment by lilydjwg** [comment]
你在命令行上，打上 fcitx5-remote -c 命令，然后切到中文模式并回事，可以切换到英文模式吗？

**Comment by ifnk** [comment]
> 你在命令行上，打上 fcitx5-remote -c 命令，然后切到中文模式并回事，可以切换到英文模式吗？

依云大佬你好！ 我在命令行上面 这样是可以的 

![dudu](https://user-images.githubusercontent.com/39295458/158979260-4a259f91-c0ca-48d3-9c65-a7046c4d9d66.gif)

**Comment by lilydjwg** [comment]
嗯。那你 `:au InsertLeavePre` 看看？

**Comment by ifnk** [comment]
> 

:au InsertLeavePre
--- Autocommands ---
 
输出的是这个，这是什么意思呀？

**Comment by lilydjwg** [comment]
说明 fcitx.vim 没有注册 InsertLeavePre 自动命令。 fcitx.vim 可能并没有加载。 `:echo g:loaded_fcitx` 显示什么呢？

**Comment by ifnk** [comment]
> 

E121: Undefined variable: g:loaded_fcitx

就是说 我 用 packer 安装  fcitx.vim 没有安装上哈？

**Comment by ifnk** [comment]
> 说明 fcitx.vim 没有注册 InsertLeavePre 自动命令。 fcitx.vim 可能并没有加载。 `:echo g:loaded_fcitx` 显示什么呢？

  use 'h-hg/fcitx.nvim'

啊 ，我用packer 装这个 nvim 就 可以啦 ，这个可以用 ，neovim 是 不能装  老的 vim 插件 么？ 还是说要设置一下 才能用？

**Comment by lilydjwg** [comment]
我不了解 nvim 和 packer 啊。

**Comment by ifnk** [comment]
> 我不了解 nvim 和 packer 啊。

解决了就行， 我在问下，我用rime + fcitx5 ,fcitx 5 有两个输入法，一 个是 默认 的 英语  ，然后 另一个是 中州韵 ，我配置成了 小鹤双拼  ，  然后 我 配置快捷键 是 左 shift 是  切换到 英语  输入法，  右 shift 是 切换到 中州韵 ， 但是 这个比较恶心 的是  中州韵 他  自己 有  英文模式和 小鹤双拼 两个子模式  ，我有时候  右shift 按的快了 就 会 切到 中州韵 自己的 英文模式 去了 

![dudu](https://user-images.githubusercontent.com/39295458/159017515-a821f11b-aaf6-48d3-ab16-9b5c5c5f46ed.gif)

大概就是这样 ，有没有办法 把 这个中州韵的 英文模式 去掉呀，就是不管按多少次 右shift ,出来的就应该是 中文 而不是 中文和英文模式轮换 ，  我只要 打中文就行了 ，英文 有 默认 的 英语  呢 

切换成中文模式后 shift 按的 多了 就会 变成 大A  
![dudu](https://user-images.githubusercontent.com/39295458/159017845-8b5c6c8c-1589-43cd-8e2f-37ef4e97cd70.gif)

**Comment by lilydjwg** [comment]
要不你不用 rime，直接用 fcitx5 的拼音？

**Comment by ifnk** [comment]
> 要不你不用 rime，直接用 fcitx5 的拼音？

我刚找遍了 fcitx5 的 设置 ，没有找到  取消 右shift 切换 小鹤双拼  中英文 轮换 的设置 ，我猜应该是 我从小鹤双拼  官方 下载 的 挂接文件里面 就是 有这个英语 的 ……   不好去呀 …… 

因为我用的不是 单纯 的 拼音 双拼 ，我 用的是  双拼 加 形码 的 小鹤双拼  ，纯 fcitx5 里面 是有内置的 小鹤双拼 的， 但是 他只有 双拼 ，没有 形码 ，只有 rime 才能 配置  这个  形码的挂接文件 

算了 不折腾 了 ……  谢谢 依云

**Comment by lilydjwg** [comment]
哦这样啊。

**Comment by Freed-Wu** [comment]
If you use neovim. Maybe you can try

- [ime.nvim](https://github.com/Freed-Wu/ime.nvim), use d-bus to switch IME
- [fcitx.nvim](https://github.com/h-hg/fcitx.nvim), call `fcitx-remote` to switch IME.
