### ISSUE TITLE
[bug] after let g:fcitx5_rime = 1, it cannot save status

### ISSUE THREAD

**Issue by Freed-Wu** [lilydjwg/fcitx.vim#33]
If I don't `let g:fcitx5_rime = 1`, it is OK.

If I `let g:fcitx5_rime = 1`, it cannot save status:

Enter insert mode, switch from us to rime, Enter normal mode, it still is rime not us.

**Comment by lilydjwg** [comment]
What does `busctl call --user org.fcitx.Fcitx5 /rime org.fcitx.Fcitx.Rime1 GetCurrentSchema` print?

**Comment by lilydjwg** [comment]
You can sleep for some time before running this command so it is called at the right time.

**Comment by Freed-Wu** [comment]
```
❯ busctl call --user org.fcitx.Fcitx5 /rime org.fcitx.Fcitx.Rime1 GetCurrentSchema
s "double_pinyin_mspy"
```

**Comment by Freed-Wu** [comment]
I only use keyboard-us and rime (with double_pinyin_mspy).

**Comment by lilydjwg** [comment]
Can you differentiate fcitx5's own status vs rime's status? You can switch between different IMs for fcitx5 (keyboard vs rime) and also you can switch between ASCII and non-ASCII mode within rime.

And `let g:fcitx5_rime = 1` should be set early (e.g. in `.vimrc`).

**Comment by Freed-Wu** [comment]
> And let g:fcitx5_rime = 1 should be set early (e.g. in .vimrc).

I have set it in the first line of vimrc. But nothing change.

> Can you differentiate fcitx5's own status vs rime's status? You can switch between different IMs for fcitx5 (keyboard vs rime) and also you can switch between ASCII and non-ASCII mode within rime.

Oh, I only use fcitx5's switch not rime's switch. Because I only use one ime (`double_pinyin_mspy`) in rime. So I don't need rime's swtich. But I use us and rime in fcitx5. So I need fcitx5's switch.
But I hope the keyboard can display correct name when it is rime. That is, it should display `double_pinyin_mspy` when I use rime, not display `rime`.

**Comment by lilydjwg** [comment]
try eb62569b3bc72795cdea918f5dda71dc8fd8ef28

**Comment by Freed-Wu** [comment]
![screen-2022-11-15-21-11-52](https://user-images.githubusercontent.com/32936898/201928205-e4d31983-f2b6-481f-b001-619d2e827160.jpg)
![screen-2022-11-15-21-12-03](https://user-images.githubusercontent.com/32936898/201928217-0d686690-4f45-4aa6-9864-919ac3f6efdc.jpg)

v:null?

**Comment by lilydjwg** [comment]
...fixed

**Comment by Freed-Wu** [comment]
Tested work. :+1:

**Comment by Freed-Wu** [comment]
Can we display both fcitx status and rime status? Such as I have two IME in fcitx: us and rime, and two schemas in rime: mspy (M$ pinyin) and japanese (rime-japanese).

Currently, It display

![Screenshot from 2024-03-17 00-13-05](https://github.com/lilydjwg/fcitx.vim/assets/32936898/5d3a1626-2c86-4ee4-b615-51770130e473)
![Screenshot from 2024-03-17 00-13-11](https://github.com/lilydjwg/fcitx.vim/assets/32936898/4042a256-58c3-4066-bb23-f9c2f8c6eaa9)


Can we display `us`, `rime:mspy`, `rime:japanese` in status bar? I want a variable to get it. TIA!

**Comment by lilydjwg** [comment]
You can modify it yourself, like this:

```patch
diff --git a/plugin/fcitx.py b/plugin/fcitx.py
index ccee097..3cbd642 100644
--- a/plugin/fcitx.py
+++ b/plugin/fcitx.py
@@ -26,6 +26,13 @@ class FcitxComm:
     else:
       return im
 
+  def current_and_rime(self):
+    im = self.fcitx.CurrentInputMethod()
+    if im == 'rime':
+      return 'rime:' + self._get_rime().GetCurrentSchema()
+    else:
+      return im
+
   def _get_rime(self):
     if self._rime is None:
       obj = self.bus.get_object('org.fcitx.Fcitx5', '/rime')
@@ -90,3 +97,7 @@ def fcitx2zh():
 @may_reconnect
 def fcitx_current_im():
   return Fcitx.current()
+
+@may_reconnect
+def fcitx_current_im_and_rime():
+  return Fcitx.current_and_rime()
diff --git a/plugin/fcitx.vim b/plugin/fcitx.vim
index 1cb837e..5b97547 100644
--- a/plugin/fcitx.vim
+++ b/plugin/fcitx.vim
@@ -49,7 +49,7 @@ elseif has('python3')
         py3 fcitx2zh()
       endfunction
       function FcitxCurrentIM()
-        return py3eval('fcitx_current_im()')
+        return py3eval('fcitx_current_im_and_rime()')
       endfunction
 
       let g:loaded_fcitx = 1
```

**Comment by Freed-Wu** [comment]
Can we add a new variable to control this behaviour?

**Comment by Freed-Wu** [comment]
For example, by default `FcitxCurrentIM()` will return `us`, `rime`. If we call `FcitxCurrentIM(arg)`,  we can get `us`, `rime:XXX`? I haven't figured out how to set format of `arg`. :smile:

**Comment by lilydjwg** [comment]
I've added another function for RIME.
