### ISSUE TITLE
[feature] change default value of g:fcitx5-remote

### ISSUE THREAD

**Issue by Freed-Wu** [lilydjwg/fcitx.vim#36]
Now, user can change `g:fcitx5-remote` to decide whether to use python-dbus or fcitx5-remote. Why not:

> if `has('python3')` and `import dbus` will not get `NoModuleError`
> `let fcitx5-remote = 0`
> else if `executable('fcitx5-remote')`
> `let fcitx5-remote = 1`
> else
> warning to let user install requirements.

? It looks better because python-dbus is faster than fcitx5-remote. TIA!

**Comment by Freed-Wu** [comment]
Such as

```vim
  try
    py3 import dbus
  catch /^Vim\%((\a\+)\)\=:E/
    if executable('fcitx5-remote')
      let g:fcitx5_remote = 1
    else
      echohl WarningMsg
      echomsg 'Please install ...'
      echohl None
    endif
  endtry
```

**Comment by lilydjwg** [comment]
I didn't implement the warning because they are annoying when you try to use the same config files across multiple systems.
