### ISSUE TITLE
是否可以忽略上次退出插入模式时使用的中文输入法 ,  在下次进入插入模式时启用英文输入法?

### ISSUE THREAD

**Issue by happy12322** [lilydjwg/fcitx.vim#37]
如果可以指定并且固定每次进入插入模式使用的输入法,  就可以实现盲操作,  不在大脑中记住上次插入模式用的输入法,  也不看显示器上输入法指示器的状态,   因为我确定进入插入模式一定是指定的输入法,  这样好像能提高一点效率?   我也不确定

再一个就是因为编辑文档中英文多,  中文少,  所以每次进入插入模式更大概率是首先需要输入英文.

是否有某个选项强制每次进入插入模式使用指定的输入法,  或者,   固定使用英文输入?

**Comment by lilydjwg** [comment]
没有这种选项，不过你可以自行更改代码。

**Comment by happy12322** [comment]
谢谢回复,  不过,  我对 vimscript 和 python 不熟,  所以搞不了.   暂时就这么用吧,  事实上,   这个插件已经非常好用了,   再次谢谢您对这个项目的辛苦和付出.
