### ISSUE TITLE
support fcitx5

### ISSUE THREAD

**Issue by meijieru** [lilydjwg/fcitx.vim#4]
Hi, thanks for your great work first.
Fcitx 5 is usable now, and I use it for my daily work. Unfortunately this plugin seems not work with it, anyway to fix it?

**Comment by lilydjwg** [comment]
I'll give fcitx 5 a try when I have time.

**Comment by meijieru** [comment]
thx

**Comment by lilydjwg** [comment]
失败了……没弄明白怎么配置输入法。

另外我看到有个 fcitx5-remote 命令，用的是 D-Bus。所以看来 Python 版需要依赖 python-dbus 了，这样跨主机通信又是个麻烦事。

VimL 版改一下命令名大概能用。

**Comment by meijieru** [comment]
貌似这个命令目前没有效果。。

**Comment by meijieru** [comment]
VimL 版现在能用了

**Comment by lilydjwg** [comment]
请见 [fcitx5 分支](https://github.com/lilydjwg/fcitx.vim/tree/fcitx5)。
