### ISSUE TITLE
不会配置...

### ISSUE THREAD

**Issue by sudoyang** [lilydjwg/fcitx.vim#5]
请问"环境变量 $FCITX_SOCKET 指定要连接的套接字路径"是什么意思？？

配置：环境变量 $FCITX_SOCKET 指定要连接的套接字路径，而非默认的。自版本 1.2.4 起，此变量若以 "@" 字符开头，则被认为是抽象套接字地址。

**Comment by lilydjwg** [comment]
不知道的话，大概说明你不需要管那部分。

**Comment by sudoyang** [comment]
哦 那就是把包解压到 .vim就可以了吧？ 再设置下ttimeoutlen。

**Comment by lilydjwg** [comment]
对。普通情况放好就可以了，设置下 ttimeoutlen 能更舒适一些。

**Comment by sudoyang** [comment]
好的， 多谢！
